function [D, HDR] = load_gre_dicom(dicomFolder, patientName)
%LOAD_GRE_DICOM Load a multi-echo GRE DICOM series and build the data struct.
%
%   [D, HDR] = load_gre_dicom(dicomFolder)
%   [D, HDR] = load_gre_dicom(dicomFolder, patientName)
%
%   Inputs
%       dicomFolder : folder containing the magnitude DICOM (.IMA) files.
%                     loadima automatically finds the paired phase folder and
%                     returns a complex multi-echo volume [nx ny nz nTE].
%       patientName : optional subject name stored in D.Patient.Name.
%
%   Output
%       D   : data structure used throughout the fat/water pipeline, with
%             acquisition metadata and D.Data.Image (complex multi-echo).
%       HDR : trimmed DICOM header array.
%
%   This is a trimmed replacement for the GRE 'Preprocess' branch of the
%   original dogexplorer.m -- it drops the study database (DD.mat) and path
%   machinery and works directly from a DICOM folder.

    if nargin < 2, patientName = ''; end

    % Load complex multi-echo image data + header
    [img, HDR, ~] = loadima(dicomFolder);

    % Determine echo times (seconds)
    TEs = zeros(1, HDR(end).EchoNumbers);
    for te = 1:size(img,3):size(img,3)*length(TEs)
        TEs(HDR(te).EchoNumbers) = HDR(te).EchoTime;
    end

    % Determine encoding steps
    PEsteps = HDR(1).NumberOfPhaseEncodingSteps;
    FEsteps = PEsteps/(HDR(1).PercentSampling/100);

    % Determine field of view
    FEfov = round(FEsteps*HDR(1).PixelSpacing(1));
    PEfov = round(FEfov*(HDR(1).PercentPhaseFieldOfView/100));

    % Determine B0 direction from patient position
    if any(strcmp(HDR(1).PatientPosition(1:2), {'FF', 'HF'})) % B0 along transverse
        B0Direction = (HDR(2).ImagePositionPatient - HDR(1).ImagePositionPatient) ...
                      ./ norm(HDR(2).ImagePositionPatient - HDR(1).ImagePositionPatient);
    else
        error('B0 direction cannot be determined from patient position.')
    end

    % Build the data structure (fields consumed by the downstream stages)
    D = struct('RawDataPath', dicomFolder, ...
                   'Patient', struct('Name', patientName, ...
                                      'Sex', HDR(1).PatientSex, ...
                                'BirthDate', HDR(1).PatientBirthDate, ...
                                   'Weight', HDR(1).PatientWeight), ...
                        'TR', HDR(1).RepetitionTime/1000, ...
                        'TE', TEs/1000, ...
                   'deltaTE', diff(TEs(1:2))/1000, ...
                  'Averages', HDR(1).NumberOfAverages, ...
                        'B0', HDR(1).ImagingFrequency/42.5774780505984, ...
                        'F0', HDR(1).ImagingFrequency, ...
                 'FlipAngle', HDR(1).FlipAngle, ...
         'BandwidthPerPixel', HDR(1).PixelBandwidth, ...
'InPlanePhaseEncodingDirection', 'ROW', ...
               'FieldOfView', [FEfov, PEfov], ...
                'MatrixSize', [FEsteps, PEsteps], ...
                 'VoxelSize', [FEfov/FEsteps, PEfov/PEsteps, HDR(1).SliceThickness], ...
                  'SliceGap', HDR(1).SpacingBetweenSlices, ...
                      'Size', size(img), ...
            'TrimmedIndices', zeros([3 2]), ...
               'B0Direction', B0Direction, ...
                     'Flags', struct('Interpolated', false, ...
                                          'Trimmed', struct('ThroughPlane', false, ...
                                                                 'InPlane', false), ...
                            'CorrectedBipolarPhase', false, ...
                           'CorrectedChemicalShift', false), ...
                      'Data', struct('Image', img));
end
